-
  name: webapp webserver and database setup
  hosts: all
  vars:
    login_user: root
    login_password: password_1

  tasks:
    -
      name: install required common packages
      apt:
        name: python3-pip
        state: present
        install_recommends: yes
      become: true
      become_method: sudo

    -
      name: install mysql server
      apt: name = {{ item }} state=present install_recommends=yes
      with_items:
        - mysql-server
      when: "'db_servers' in group_names"
      become: true
      become_method: sudo

    -
      name: install PyMySQL using pip. Ansible mysql_db modules require this library
      pip:
        name: PyMySQL
      when: "'db_servers' in group_names"
      become: true
      become_method: sudo

    -
      name: start mysql service
      service:
        name: mysql
        state: started
        enabled: yes
      when: "'db_servers' in group_names"
      become: true
      become_method: sudo

    -
      name: create USERMANAGER database
      mysql_db:
        name: usermanager
        state: present
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"
      when: "'db_servers' in group_names"

    -
      name: create database user with passwssword and all database privileges to the usermanager database
      mysql_user:
        name: usermanager_db_user
        password: password_1
        host: %
        priv: 'usermanager.*:ALL,GRANT'
        state: present
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"
      when: "'db_servers' in group_names"
