Vagrant.configure("2") do |config|

	config.vm.define "controller" do |controller|

		controller.vm.box = "minimal/xenial64"
		controller.vm.network "private_network", ip: "192.168.50.4"
    controller.vm.network "public_network"

		controller.vm.provider :virtualbox do |vb|
	  	vb.customize [
	    		"modifyvm", :id,
	    		"--cpuexecutioncap", "50",
	    		"--memory", "256",
	  	]
	  end
	end

	config.vm.define "target" do |target|

		target.vm.box = "minimal/xenial64"
		target.vm.network "private_network", ip: "192.168.50.5"
	  target.vm.network "public_network"

		target.vm.provider :virtualbox do |vb|
	  	vb.customize [
	    		"modifyvm", :id,
	    		"--cpuexecutioncap", "50",
	    		"--memory", "256",
	  	]
	  end
	end

	config.vm.define "target_2" do |target_2|

		target_2.vm.box = "minimal/xenial64"
		target_2.vm.network "private_network", ip: "192.168.50.6"
	  target_2.vm.network "public_network"

		target_2.vm.provider :virtualbox do |vb|
	  	vb.customize [
	    		"modifyvm", :id,
	    		"--cpuexecutioncap", "50",
	    		"--memory", "256",
	  	]
	  end
	end

end
