Vagrant.configure("2") do |config|

	config.vm.define "controller" do |controller|

		controller.vm.box = "minimal/xenial64"
		controller.vm.network "private_network", ip: "192.168.50.4"
    controller.vm.network "public_network"

		controller.vm.provider :virtualbox do |vb|
	  	vb.customize [
	    		"modifyvm", :id,
	    		"--cpuexecutioncap", "50",
	    		"--memory", "256",
	  	]
	  end
	end

	config.vm.define "target_1" do |target_1|

		target_1.vm.box = "minimal/xenial64"
		target_1.vm.network "private_network", ip: "192.168.50.5"
	  target_1.vm.network "public_network"

		target_1.vm.provider :virtualbox do |vb|
	  	vb.customize [
	    		"modifyvm", :id,
	    		"--cpuexecutioncap", "50",
	    		"--memory", "256",
	  	]
	  end
	end

	config.vm.define "target_2" do |target_2|

		target_2.vm.box = "minimal/xenial64"
		target_2.vm.network "private_network", ip: "192.168.50.6"
	  target_2.vm.network "public_network"

		target_2.vm.provider :virtualbox do |vb|
	  	vb.customize [
	    		"modifyvm", :id,
	    		"--cpuexecutioncap", "50",
	    		"--memory", "256",
	  	]
	  end

	end
	config.vm.define "target_3" do |target_3|

		target_3.vm.box = "minimal/xenial64"
		target_3.vm.network "private_network", ip: "192.168.50.7"
		target_3.vm.network "public_network"

		target_3.vm.provider :virtualbox do |vb|
			vb.customize [
					"modifyvm", :id,
					"--cpuexecutioncap", "50",
					"--memory", "256",
			]
		end
	end
end
