-
  name:                     flask-app webserver and database setup
  hosts:                    all

  tasks:
    -
      name:                 install required common packages
      apt:
        name:               python3-pip
        state:              present
        install_recommends: yes
      become:               true
      become_method:        sudo
    -
      include:              tasks/deploy_db.yaml
